# Generated by Django 2.2.2 on 2020-10-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_images_missingpets'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.MissingPets'),
        ),
    ]
