# Generated by Django 2.2.2 on 2020-10-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201012_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='p_id',
            new_name='missing_pets_id',
        ),
    ]
