# Generated by Django 2.2.2 on 2020-10-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_images_missing_pets_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='missing_pets_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.MissingPets'),
        ),
    ]
