# Generated by Django 2.2.2 on 2020-09-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='datejoined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='lastlogin')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_pet_owner', models.BooleanField(default=False)),
                ('is_vet', models.BooleanField(default=False)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('is_rescuer', models.BooleanField(default=False)),
                ('pro_pic', models.ImageField(upload_to='uploads/pro-pic/')),
                ('certificates', models.FileField(upload_to='uploads/certificates/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
