# Generated by Django 2.2.2 on 2020-10-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200928_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificates',
            field=models.FileField(default=None, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(upload_to='pro-pic/'),
        ),
    ]
