# Generated by Django 2.2.2 on 2020-10-03 23:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201002_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(upload_to=users.models.user_directory_path),
        ),
    ]
