# Generated by Django 2.2.2 on 2020-10-04 01:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201003_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificates',
            field=models.FileField(default=None, upload_to=users.models.user_certs),
        ),
    ]
