# Generated by Django 2.2.2 on 2020-10-07 23:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201003_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=users.models.user_certs)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='certificates',
        ),
        migrations.AddField(
            model_name='user',
            name='certificates',
            field=models.ManyToManyField(to='users.FeedFile'),
        ),
    ]
