# Generated by Django 2.2.2 on 2020-10-09 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201009_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedfile',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedfile',
            name='file',
            field=models.FileField(upload_to=users.models.user_certs),
        ),
    ]
